apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: veria-api
  labels:
    environment: ${ENVIRONMENT}
  annotations:
    run.googleapis.com/launch-stage: GA
spec:
  template:
    metadata:
      annotations:
        # Autoscaling
        autoscaling.knative.dev/minScale: ${MIN_INSTANCES}
        autoscaling.knative.dev/maxScale: ${MAX_INSTANCES}
        # CPU allocation
        run.googleapis.com/cpu-throttling: "false"
        # Startup probe
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      serviceAccountName: veria-api@${GCP_PROJECT_ID}.iam.gserviceaccount.com
      containers:
        - name: veria-api
          image: ${IMAGE_URL}
          ports:
            - name: http1
              containerPort: 3001
          env:
            - name: NODE_ENV
              value: ${ENVIRONMENT}
            - name: SERVICE
              value: gateway
            - name: PORT
              value: "3001"
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-url
                  key: latest
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: redis-url
                  key: latest
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: latest
            - name: ALCHEMY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: alchemy-api-key
                  key: latest
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret-key
                  key: latest
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: stripe-webhook-secret
                  key: latest
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry-dsn-backend
                  key: latest
            - name: DATADOG_API_KEY
              valueFrom:
                secretKeyRef:
                  name: datadog-api-key
                  key: latest
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
