
services:
  postgres:
    image: postgres:16-alpine
    container_name: veria_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: veria
      POSTGRES_USER: veria
      POSTGRES_PASSWORD: veria_dev_2024
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./packages/database/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U veria"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: infra/docker/compliance.Dockerfile
    image: compliance-mw:dev
    container_name: compliance_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://veria:veria_dev_2024@postgres:5432/veria
    volumes:
      - ./packages/compliance_middleware:/app/packages/compliance_middleware
    command: ["uvicorn", "packages.compliance_middleware.app:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      postgres:
        condition: service_healthy

  edge:
    build:
      context: ./packages/edge_proxy
    container_name: edge_proxy
    ports:
      - "8080:8080"
    env_file:
      - .env
    command: ["node", "dist/index.js"]
    depends_on:
      - api

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  postgres_data:
  qdrant_data:
