apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: veria-investor
  labels:
    environment: ${ENVIRONMENT}
    app: investor-portal
  annotations:
    run.googleapis.com/launch-stage: GA
spec:
  template:
    metadata:
      annotations:
        # Autoscaling
        autoscaling.knative.dev/minScale: ${MIN_INSTANCES}
        autoscaling.knative.dev/maxScale: ${MAX_INSTANCES}
        # CPU allocation
        run.googleapis.com/cpu-throttling: "false"
        # Startup probe
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      serviceAccountName: veria-investor@${GCP_PROJECT_ID}.iam.gserviceaccount.com
      containers:
        - name: veria-investor
          image: ${IMAGE_URL}
          ports:
            - name: http1
              containerPort: 3002
          env:
            - name: NODE_ENV
              value: ${ENVIRONMENT}
            - name: SERVICE
              value: investor
            - name: PORT
              value: "3002"
            - name: FEATURE_INVESTOR_PORTAL
              value: "${FEATURE_INVESTOR_PORTAL}"
            - name: NEXT_PUBLIC_API_URL
              value: ${API_GATEWAY_URL}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: latest
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry-dsn-frontend
                  key: latest
                  optional: true
            - name: DATADOG_API_KEY
              valueFrom:
                secretKeyRef:
                  name: datadog-api-key
                  key: latest
                  optional: true
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.25"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3002
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3002
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
  traffic:
    - percent: 100
      latestRevision: true