version: '3.9'
services:
  audit:
    image: node:20-alpine
    working_dir: /app
    command: sh -lc "corepack enable && pnpm i && pnpm --filter @veria/audit-log-writer dev"
    ports: ["3005:3005"]
    volumes: [".:/app"]

  compliance:
    image: node:20-alpine
    working_dir: /app
    environment:
      - AUDIT_WRITER_URL=http://audit:3005/audit
    command: sh -lc "corepack enable && pnpm i && pnpm --filter @veria/compliance-service dev"
    ports: ["3004:3004"]
    volumes: [".:/app"]
    depends_on: [audit]

  identity:
    image: node:20-alpine
    working_dir: /app
    command: sh -lc "corepack enable && pnpm i && pnpm --filter @veria/identity-service dev"
    ports: ["3002:3002"]
    volumes: [".:/app"]

  policy:
    image: node:20-alpine
    working_dir: /app
    command: sh -lc "corepack enable && pnpm i && pnpm --filter @veria/policy-service dev"
    ports: ["3003:3003"]
    volumes: [".:/app"]

  gateway:
    image: node:20-alpine
    working_dir: /app
    environment:
      - IDENTITY_URL=http://identity:3002
      - POLICY_URL=http://policy:3003
      - COMPLIANCE_URL=http://compliance:3004
    command: sh -lc "corepack enable && pnpm i && pnpm --filter @veria/gateway dev"
    ports: ["3001:3001"]
    volumes: [".:/app"]
    depends_on: [identity, policy, compliance]

  frontend:
    image: node:20-alpine
    working_dir: /app
    environment:
      - NEXT_PUBLIC_GATEWAY_URL=http://localhost:3001
    command: sh -lc "corepack enable && pnpm i && pnpm --filter @veria/frontend dev"
    ports: ["3000:3000"]
    volumes: [".:/app"]
    depends_on: [gateway]
