name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - gateway
          - policy-service
          - compliance-service
          - identity-service
          - audit-log-writer

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check ${{ matrix.service }}
        run: pnpm --filter @veria/${{ matrix.service }} typecheck
        continue-on-error: true

      - name: Test ${{ matrix.service }}
        run: pnpm --filter @veria/${{ matrix.service }} test
        continue-on-error: true

  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check frontend
        run: pnpm --filter @veria/frontend typecheck
        continue-on-error: true

      - name: Build frontend
        run: pnpm --filter @veria/frontend build
        continue-on-error: true
