
name: ci

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Poetry
        run: pip install poetry
      - name: Install deps
        run: poetry install
      - name: Lint
        run: poetry run ruff check packages/compliance_middleware
      - name: Tests
        run: poetry run pytest -q
